<?php

return [
    [
        'name' => 'douyinappid',
        'title' => '抖音小程序AppID',
        'type' => 'string',
        'content' => [],
        'value' => 'ttd4f6a24b4bc7991601',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'douyinappsecret',
        'title' => '抖音小程序AppSecret',
        'type' => 'string',
        'content' => [],
        'value' => '14a42421118395ddca82f9b86cdb9be7363561ed',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'wxappid',
        'title' => '微信小程序AppID',
        'type' => 'string',
        'content' => [],
        'value' => 'wxad9cb302c735a261',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'wxappsecret',
        'title' => '微信小程序AppSecret',
        'type' => 'string',
        'content' => [],
        'value' => '5e434a557f859c0841900306f47cf41a',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'couponsn',
        'title' => '微信支付商户号ID',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'paykey',
        'title' => '微信支付商户的密钥',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'cert',
        'title' => '微信支付API证书cert',
        'type' => 'file',
        'content' => [],
        'value' => '',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'key',
        'title' => '微信支付API证书key',
        'type' => 'file',
        'content' => [],
        'value' => '',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
];
